
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: xiongfeitan
google_analytics: xiongfeitan

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nemo

description: Jekyll Theme
author:
  name: XiongFeiTan
  email: xiongfeitan@qq.com
  github: XiongFeiTan
  twitter: XiongFeiTan
  pinterest: XiongFeiTan
  linkedin: XiongFeiTan
  bio:  If Winter comes, can Spring be far behind? --Percy Bysshe Shelley 
  

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:




