
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: joekojoe
google_analytics: joekojoe

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nemo

description: Jekyll Theme
author:
  name: Nemo
  email: xiongfeitan@qq.com
  github: Nemo
  twitter: Nemo
  pinterest: Nemo
  linkedin: Nemo
  bio:  If Winter comes, can Spring be far behind? --Percy Bysshe Shelley 
  

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:




