# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: joekojoe
google_analytics: joekojoe

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: joekojoe

description: Stylish Jekyll Theme
author:
  name: joekojoe
  email: 761334345@qq.com
  github: joekojoe
  twitter: joekojoe
  pinterest: joekojoe
  linkedin: joekojoe
  bio: learn create blog !
  

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
